### ISSUE TITLE
Why I can't control my bluetooth device volume?

### ISSUE THREAD

**Issue by JuanZoran** [IbrahimElsayed26498/volume-control#1]
A nice widget that helps me solve the volume problem.

But I found that when I use a Bluetooth headset, then it only can adjust the computer volume instead of my Bluetooth device ...
Is there any solution to that?

**Comment by tamawy** [comment]
Thank you.
I didn't try to use Bluetooth headset, but I will try to solve this problem Insha'Allah.

**Comment by JuanZoran** [comment]
this is what I am using to adjust the volume, maybe can be helpful:

this works well when I use headset
```lua
    awful.key({}, 'XF86AudioRaiseVolume',  function() awful.spawn.with_shell('pactl set-sink-volume @DEFAULT_SINK@ +5%') end, { description = 'Increase volume', group = 'client' }),
    awful.key({}, 'XF86AudioLowerVolume',  function() awful.spawn.with_shell('pactl set-sink-volume @DEFAULT_SINK@ -5%') end, { description = 'Decrease volume', group = 'client' }),

```

**Comment by tamawy** [comment]
OK, but does this work when removing headset? or just when using headset?

**Comment by JuanZoran** [comment]
it works all the time

**Comment by tamawy** [comment]
Good.
I will try and push it.

**Comment by JuanZoran** [comment]
Thanks for that!

**Comment by tamawy** [comment]
You're welcome. :)

**Comment by tamawy** [comment]
Issue fixed. Try it.

I appreciate you efforts.
